# This is a basic workflow to help you get started with Actions
name: learn-aws-patch-manager

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches:
      - main

env:
  
  AWS_REGION : "us-east-1" #Change to reflect your Region  

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: write    # This is required for actions/checkout
jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3  
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::626635428534:role/GithubAction #change to reflect your IAM roleâ€™s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: |
          terraform init
          terraform fmt
          terraform validate
          terraform plan
          echo "Checking ec2_ssm_profile..."
          if aws iam get-instance-profile --instance-profile-name ec2_ssm_profile >/dev/null 2>&1; then
              ROLES=$(aws iam get-instance-profile --instance-profile-name ec2_ssm_profile --query 'InstanceProfile.Roles[*].RoleName' --output text)
              for ROLE in $ROLES; do
                  aws iam remove-role-from-instance-profile --instance-profile-name ec2_ssm_profile --role-name "$ROLE"
              done
              sleep 2
              aws iam delete-instance-profile --instance-profile-name ec2_ssm_profile
          else
              echo "Profile doesn't exist"
          fi       
          terraform apply --auto-approve
        working-directory: infra_terraform

      - name: Git Config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/davidawcloudsecurity/learn-aws-patch-manager.git                   
          # Get the latest commit hash
          COMMIT_HASH=$(git rev-parse --short HEAD)          
          
          # Fetch the latest changes from the remote 'destroy/main' branch
          git status
          echo "git fetch"
          git fetch origin destroy/main
          git add main.tf
          git commit -m "random-${COMMIT_HASH}" --allow-empty
          cp main.tf main.tf.origin
          git stash
          echo "git checkout"
          git checkout destroy/main
          echo "git merge"
          git merge origin/destroy/main
          mv main.tf.origin main.tf
          if [ -f terraform.tfstate ]; then
            mv terraform.tfstate state/
            git add state
          fi
          git add main.tf
          git commit -m "random-${COMMIT_HASH}" --allow-empty
          # Push the changes to the 'destroy/main' branch
          git push origin destroy/main
        working-directory: infra_terraform

      - name: Terraform Destroy on Failure
        if: failure()
        run: |
          terraform destroy -auto-approve -input=false
          echo "Check if AmazonSSMManagedInstanceRole exist"
          if [ -n "$(aws iam list-roles --query 'Roles[*].RoleName' | grep AmazonSSMManagedInstanceRole | sed 's/[",]//g')" ]; then
            aws iam delete-role --role-name $(aws iam list-roles --query 'Roles[*].RoleName' | grep AmazonSSMManagedInstanceRole | sed 's/[",]//g')
          fi
          echo "Check if AmazonSSMManagedInstanceProfile exist"
          if [ -n "$(aws iam list-instance-profiles --query InstanceProfiles[*].InstanceProfileName | grep AmazonSSMManagedInstanceProfile | sed 's/[",]//g')" ]; then
            aws iam delete-instance-profile --instance-profile-name $(aws iam list-instance-profiles --query InstanceProfiles[*].InstanceProfileName | grep AmazonSSMManagedInstanceProfile | sed 's/[",]//g')
          fi
        working-directory: infra_terraform          
          
